#!/usr/bin/env python3

import importlib
import os
import argparse
import sys
from common import local_runtime

def load_modules():
  module_dir = os.path.dirname(os.path.realpath(__file__))
  dirs = os.listdir(module_dir + '/modules')
  mods = {}
  # load submodules into dict
  # submodules must have entry.py with 2 functions
  # get_args(subparser) which fills out its required args
  # run(args) which actually runs it
  for d in dirs:
    if not os.path.isdir(module_dir + '/modules/'+d):
      continue
    if d.startswith('_') or d.startswith('common'):
      continue
    # e.g modules.snap_align.entry
    path = 'modules.' + d + '.entry'
    mod = importlib.import_module(path)
    mods[d] = mod
  return mods

def get_args(modules):

  parent_parser = argparse.ArgumentParser(description="Persona -- High-Performance Bioinformatics",
                                   formatter_class=argparse.ArgumentDefaultsHelpFormatter, add_help=False)

  parent_parser.add_argument("dataset", help="The AGD json metadata file describing the dataset")

  parser = argparse.ArgumentParser()

  subparsers = parser.add_subparsers(help="Available modes", dest="modes")

  local_subparser = subparsers.add_parser("local", help="Run Personal locally")

  local_subparsers = local_subparser.add_subparsers(help="Available modules; use $ persona <command> -h for details", dest="local")

  # have each submodule define its own args
  for name, mod in modules.items():
    helpmsg = mod.get_tooltip()
    subparser = local_subparsers.add_parser(name, help=helpmsg, parents=[parent_parser])
    mod.get_args(subparser)
    subparser.set_defaults(func=local_runtime.execute)
  
  dist_subparser = subparsers.add_parser("dist", help="Run Persona on a cluster")
  setup_subparser = subparsers.add_parser("setup", help="Setup Persona on a cluster")


  args = parser.parse_args()
  print(args)
  return args

if __name__ == "__main__":
  if (len(sys.argv) == 1):
    msg = (
         "              ___                                 \n"
         "-. .-.   .   / _ \___ _ __ ___  ___  _ __   __ _  .-. .-.   .\n"
         "||\|||\ /|  / /_)/ _ \ '__/ __|/ _ \| '_ \ / _` | |||\|||\ /|\n"
         "|/ \|||\|| / ___/  __/ |  \__ \ (_) | | | | (_| | ||/ \|||\||\n"
         "~   `-~ `- \ /   \___|_|  |___/\___/|_| |_|\__,_| -`   `-~ `-\n"
    )
    print(msg)
    print("Persona -- High-Performance Bioinformatics")
    print("Use $ persona -h to see available options\n")
    exit(0)
  modules = load_modules()
  args = get_args(modules)
  #import ipdb; ipdb.set_trace()
  args.func(args, modules)
 
